name: 🚀 Deploy website on push

on:
  push:
    branches: [ ftp ]
  pull_request:
    branches: [ ftp ]

jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code 
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftps
        port: ${{ secrets.FTP_PORT }}
        exclude: .git*
          - .git*/**
          - .github
